### ISSUE TITLE
能否也提供一份 plaintext 版本的？

### ISSUE THREAD

**Issue by aflyhorse** [poctopus/gfwlist-plus#2]
SwitchyOmega 订阅功能不会自动解码 base64
祝好

**Comment by poctopus** [comment]
直接用base64的解码工具解码一下就可以了。

**Comment by aflyhorse** [comment]
“SwitchyOmega订阅功能不会自动解码”
如果你这做出来不是让浏览器订阅的那当我没说

**Comment by poctopus** [comment]
等我研究一下switchyOmega的使用方法。

**Comment by poctopus** [comment]
楼主，我用chrome的的Proxy SwitchyOmega，已经用一个版本可以正常导入了，你可以试试看。
https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif/related?hl=en

gfwlist-plust地址：http://www.aladown.com/gfwlist-plus.txt

**Comment by aflyhorse** [comment]
测试了下，第一行不能动，必须是```[AutoProxy 0.2.9]```，否则不识别
此外，aladown.com 也是你的站？

**Comment by poctopus** [comment]
> 测试了下，第一行不能动，必须是`[AutoProxy 0.2.9]`，否则不识别
> 此外，aladown.com 也是你的站？

已经将原始的plaintext版本发送到你的邮箱了。
aladown.com是我的网站。

**Comment by aflyhorse** [comment]
感谢修正

**Comment by aflyhorse** [comment]
借地报一个域名 wiktionary.org 维基词典
祝好，
