### ISSUE TITLE
SmartProxy - 代理规则订阅 不能添加

### ISSUE THREAD

**Issue by yfdyh000** [poctopus/gfwlist-plus#3]
https://chrome.google.com/webstore/detail/smartproxy/jogcnplbkgkfdakgdenhlpcfhjioidoj
好像是`[GFW-PLUS 0.0.7]`而非`[AutoProxy 0.2.9]`的原因。

https://github.com/salarcode/SmartProxy/blob/bf01c70e10f5ca0cc569b21e2c6ffdd45c4ebb31/src/lib/RuleImporter.ts#L420

**Comment by poctopus** [comment]
在我的机器上跑了一下没有问题，先暂时用这个连接，楼主测试一下，是否OK，OK了，我再更新。
https://www.aladown.com/gfwlist-plus.txt

**Comment by yfdyh000** [comment]
> 在我的机器上跑了一下没有问题，先暂时用这个连接，楼主测试一下，是否OK，OK了，我再更新。
> https://www.aladown.com/gfwlist-plus.txt

这个可以。

**Comment by poctopus** [comment]
> > 在我的机器上跑了一下没有问题，先暂时用这个连接，楼主测试一下，是否OK，OK了，我再更新。
> > https://www.aladown.com/gfwlist-plus.txt
> 
> 这个可以。

将今天新增的域名和这个功能一起更新github系统中了。

**Comment by yfdyh000** [comment]
> > > 在我的机器上跑了一下没有问题，先暂时用这个连接，楼主测试一下，是否OK，OK了，我再更新。
> > > https://www.aladown.com/gfwlist-plus.txt
> > 
> > 
> > 这个可以。
> 
> 将今天新增的域名和这个功能一起更新github系统中了。

👍
