### ISSUE TITLE
可否出一个明文版本。我自己复制到黑名单列表里（梅林386固件科学上网插件）

### ISSUE THREAD

**Issue by AlexWingCG** [poctopus/gfwlist-plus#5]
可否出一个明文版本。我自己复制到黑名单列表里（梅林386固件科学上网插件）就是xxx.com这种的

**Comment by poctopus** [comment]
都是base64加密的，自己手工解密一下就可以了。或者去https://www.sojson.com/base64.html   这里直接解密就可以。
